### ISSUE TITLE
Selection box and hover effects not showing on dark theme

### ISSUE THREAD

**Issue by SteMoeller** [FlowingCode/YearMonthCalendarAddon#11]
Hi and thanks for that great plugin! 
I encountered a problem using the dark theme (Lumo.Dark) together with the component: 
On the light theme the selected month gets a blue box, on the dark theme it doesn't. Same applies to hover effects... I figured out hot to reconfigure the hover effects and selection thing but it also only shows up on the Light theme (or no theme at all)...

**Comment by javier-godoy** [comment]
Hello. Which version of the addon and Vaadin are you using? Note that hover effects currently don't work with Vaadin 23 (likely because of some change in `vaadin-month-calendar` component)

Regarding the blue box, I've just tested it in the demo sites for V22 and 23 by manually switching the theme with `document.documentElement.setAttribute("theme", "dark");` and it's displayed.
![image](https://user-images.githubusercontent.com/11554739/160282867-44f4b860-52d2-42a0-b5ca-43813c151fe5.png)

**Comment by SteMoeller** [comment]
Hi Javier,
thanks for the fast feedback. I uploaded a demo app to show the problem: https://github.com/SteMoeller/vaadinCalendarWidgetDemo
It uses the same versions I use in my "real" application. The demo has the same "problem" as I do in my other app.

Besides the bug: 
How do I need to style the css that the hover things still work when I use the class name generator to highlight certain days (i did it using random in my uploaded demo, the random styled dates don't show an hover effect neither on LIGHT nor on DARK mode...)

**Comment by SteMoeller** [comment]
Just found the problem: the "z-index: -1" kills the thing in the dark mode. 
If I "unset" the z-index on the ::before parts, the hover and selection box works again...

**Comment by SteMoeller** [comment]
Can I assist somehow on fixing the issue? Did u take a look at my demo project?

**Comment by SteMoeller** [comment]
Thanks a lot for all your tests and examples... Now it works as intended!
