### ISSUE TITLE
Bug with YearMonthField ValueChangeListener

### ISSUE THREAD

**Issue by Jukisawa** [FlowingCode/YearMonthCalendarAddon#57]
from march to april the ValueChangeListener isnt called and if you go from april to may then the ValueChangeListener ist called with april instead of may.

**Comment by javier-godoy** [comment]
Hello. Which version of the add-on and Vaadin are you using. I attempted to reproduce it in Vaadin 22 (add-on 2.3.0) and it seems to work as expected.

```
YearMonthField field = new YearMonthField();

add(field);
field.addValueChangeListener(ev -> {
      Notification.show(ev.getValue().toString());
});
```

**Comment by Jukisawa** [comment]
Vaadin 23 and Version 2.3.1 of the addon. 

Note you can check your online demo https://addonsv23.flowingcode.com/year-month-calendar/inline-date-picker wich has the same issue.

**Comment by Jukisawa** [comment]
My Code looks something like this:

```
    private final YearMonthField monthField = new YearMonthField();
    private final MonthCalendar calendar = new MonthCalendar(YearMonth.now());

    private void updateCalendar(
        AbstractField.ComponentValueChangeEvent<YearMonthField, YearMonth> monthFieldValueChangeEvent) {

        calendar.setYearMonth(monthFieldValueChangeEvent.getValue());

    }

    void addCalendar() {

        monthField.addValueChangeListener(this::updateCalendar);

        calendar.setReadOnly(true);
        calendar.setSizeFull();

        add(monthField);
        add(calendar);
    }
```

when i click on the right button from march to april then nothing happens. If i click it again then it say its may but the calendar shows april.

**Comment by javier-godoy** [comment]
Hello. I was not able to reproduce it. Can you please upload a sample application demonstrating the issue?

![month-calendar](https://user-images.githubusercontent.com/11554739/230956576-eacb8136-dfb9-4e22-a3ff-37d564f6ebab.gif)

- Open a view with your code above. (Since the current month is now April, it displays the calendar for April 2023 instead of March)
- When I click on the right button from april to May, both components are updated to May.
- When I click on the right button from May to June, both components are updated to June.

**Comment by Jukisawa** [comment]
Bug is gone with newer version
